### ISSUE TITLE
Doc2vec模型的问题

### ISSUE THREAD

**Issue by yexue008** [bigzhao/Keyword_Extraction#1]
老师你好，看您的代码中使用到了Doc2vec的模型，请问方便分享一下训练好的模型吗？非常感谢。

**Comment by bigzhao** [comment]
你好，那个文件我漏传了，现在补上
链接：https://pan.baidu.com/s/17ZYAbTeqsXXq-hE3z3QqmA 
提取码：0ciw 
PS: 原理是先切词然后用gensim默认参数训练的，迭代次数少所以几分钟就训练好了。

**Comment by yexue008** [comment]
非常感谢你的帮助，请问，您用gensim训练的文本集是哪个数据集？用的是英文的是吗？

**Comment by bigzhao** [comment]
不是啊，用的是这个比赛提供的中文新闻语料库。

**Comment by yexue008** [comment]
哦哦，明白啦，太感谢了哈

**Comment by pk3725069** [comment]
请问一下，doc2vec 的训练的词向量，你使用是已经预训练好的word2vec词向量，还是doc2vec模型自动初始化的？
